### ISSUE TITLE
Not displaying images 

### ISSUE THREAD

**Issue by Westlake-1** [miya0001/cardboard#5]
I have installed Cardboard and it is working perfectly in Firefox and Safari on my laptop, and Safari on my iPhone. In Safari on my iPad, the page loads then before the 360 images display, the page reloads with a message saying that something went wrong on the page. On Chrome and Opera on my laptop, nothing appears, not even a blank space, where the 360 images should be.

The page URL is http://westlakemedia.ca/video/360-test-page/

**Comment by miya0001** [comment]
It looks working fine for me. 😄
